# Simple GitLab CI/CD Pipeline
stages:
  - test
  - build
  - deploy

variables:
  UV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/uv"

# Cache uv packages
cache:
  paths:
    - .cache/uv
    - .venv/

# Run tests
test:
  stage: test
  image: python:3.10
  before_script:
    - pip install uv
    - uv venv
    - source .venv/bin/activate
    - uv pip install -e .
    - uv pip install -e ".[dev]"
  script:
    - pytest tests/ -v
    - ruff check src tests
    - black --check src tests
  only:
    - develop
    - main
    - merge_requests

# Build Docker image
build_docker:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - docker build -t plant-disease-detector:$CI_COMMIT_SHA .
    - docker save plant-disease-detector:$CI_COMMIT_SHA > image.tar
  artifacts:
    paths:
      - image.tar
    expire_in: 1 hour
  only:
    - develop
    - main

# Deploy Streamlit app
deploy_app:
  stage: deploy
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - docker load < image.tar
    - docker run -d --name plant-disease-app -p 8501:8501 plant-disease-detector:$CI_COMMIT_SHA
    - echo "App deployed at http://localhost:8501"
  dependencies:
    - build_docker
  only:
    - main
  when: manual
