stages:  
  - test_simple

variables:
  UV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/uv"

# Simple test
test_basic:
  stage: test_simple
  image: python:3.10
  script:
    - echo "Installing uv..."
    - pip install uv
    - echo "Creating venv..."
    - uv venv
    - echo "Activating venv..."
    - source .venv/bin/activate
    - echo "Installing package..."
    - uv pip install -e . || (echo "Install failed, trying with verbose output..." && uv pip install -e . -v)
    - echo "Running basic import test..."
    - python -c "import plant_disease; print('Import successful!')"
  only:
    - main