#seed: 42
#model_name: google/vit-base-patch16-224-in21k
#dataset_name: GVJahnavi/PlantVillage_dataset

# NUEVO: rutas dentro del proyecto
#model_dir: model
#data_cache_dir: data

#num_epochs: 5
#batch_size: 32
#lr: 5.0e-5
#weight_decay: 0.01
#train_val_test_split: [0.7, 0.15, 0.15]
#image_size: 224
#push_to_hub: false


# Entrenamiento rápido / smoke test
seed: 42

# Usa el dataset remoto de HF o una carpeta local con imágenes (imagefolder)
dataset_name: "plantvillage"        # o "D:/ruta/a/tu/carpeta" si usas carpeta local
data_cache_dir: "./data"

# Toma una fracción pequeña para acelerar
train_val_test_split: [0.05, 0.01, 0.94]   # ~5% train, 1% val, 94% test

# Modelo (elige uno)
# Muy rápido (recomendado para CPU):
#model_name: "facebook/deit-tiny-patch16-224"
# Alternativa (más pesado y lento):
model_name: "google/vit-base-patch16-224-in21k"

image_size: 224

# Hiperparámetros ligeros
batch_size: 4
lr: 5.0e-5
weight_decay: 0.01
num_epochs: 1

# Dónde guardar
model_dir: "artifacts/quick_run"